/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author felipeiise
 */
public class guiMenu extends javax.swing.JFrame {

    /**
     * Creates new form guiMenu
     */
    public guiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCurso = new javax.swing.JMenuItem();
        menuTurma = new javax.swing.JMenuItem();
        menuInstrutor = new javax.swing.JMenuItem();
        menuAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAlocarInstrutor = new javax.swing.JMenuItem();
        menuEfetuarMatricula = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");

        jMenu1.setText("Cadastros");

        menuCurso.setText("Curso");
        menuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCursoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCurso);

        menuTurma.setText("Turma");
        menuTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(menuTurma);

        menuInstrutor.setText("Instrutor");
        menuInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInstrutorActionPerformed(evt);
            }
        });
        jMenu1.add(menuInstrutor);

        menuAluno.setText("Aluno");
        menuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(menuAluno);
        jMenu1.add(jSeparator1);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações");

        menuAlocarInstrutor.setText("Alocar Instrutor");
        jMenu2.add(menuAlocarInstrutor);

        menuEfetuarMatricula.setText("Efetuar Matrícula");
        jMenu2.add(menuEfetuarMatricula);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCursoActionPerformed
        new guiCurso().setVisible(true);
    }//GEN-LAST:event_menuCursoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTurmaActionPerformed
        new guiTurma().setVisible(true);
    }//GEN-LAST:event_menuTurmaActionPerformed

    private void menuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunoActionPerformed
        new guiAluno().setVisible(true);
    }//GEN-LAST:event_menuAlunoActionPerformed

    private void menuInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInstrutorActionPerformed
        new guiInstrutor().setVisible(true);
    }//GEN-LAST:event_menuInstrutorActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAlocarInstrutor;
    private javax.swing.JMenuItem menuAluno;
    private javax.swing.JMenuItem menuCurso;
    private javax.swing.JMenuItem menuEfetuarMatricula;
    private javax.swing.JMenuItem menuInstrutor;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuTurma;
    // End of variables declaration//GEN-END:variables
}
